package dev.home.platform.service;

import dev.home.platform.config.PlatformProperties;
import dev.home.platform.domain.PipelineInstance;
import dev.home.platform.domain.PipelineInstanceRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * Creates/updates openspec change and artifacts (proposal, design, specs, tasks).
 */
@Service
public class OpenspecService {

    private static final Logger log = LoggerFactory.getLogger(OpenspecService.class);
    private static final List<String> CAPABILITIES = Arrays.asList(
            "requirement-input", "design-generation", "openspec-integration", "cursor-integration", "pipeline-orchestration");

    private final PlatformProperties config;
    private final PipelineInstanceRepository repository;

    public OpenspecService(PlatformProperties config, PipelineInstanceRepository repository) {
        this.config = config;
        this.repository = repository;
    }

    /**
     * Ensure change exists, write/update proposal, design, specs, tasks. Returns change dir path.
     */
    public String runOpenspec(String instanceId) throws IOException, InterruptedException {
        PipelineInstance p = repository.findByInstanceId(instanceId)
                .orElseThrow(() -> new IllegalArgumentException("Instance not found: " + instanceId));
        String changeName = toChangeName(p.getInstanceId());
        Path workDir = Paths.get(config.getOpenspecWorkDir()).toAbsolutePath();
        ensureOpenspecInitialized(workDir);
        Path changeDir = workDir.resolve("openspec").resolve("changes").resolve(changeName);

        if (!changeDir.toFile().exists()) {
            int exit = run(workDir, "openspec", "new", "change", changeName);
            if (exit != 0) throw new IOException("openspec new change failed with exit " + exit);
            log.info("Created openspec change: {}", changeName);
        } else {
            log.info("Reusing existing openspec change: {}", changeName);
        }

        writeFile(changeDir.resolve("proposal.md"), buildProposal(p));
        writeFile(changeDir.resolve("design.md"), buildDesignFromRequirement(p.getRequirementText() != null ? p.getRequirementText().trim() : ""));
        for (String cap : CAPABILITIES) {
            Path specPath = changeDir.resolve("specs").resolve(cap).resolve("spec.md");
            Files.createDirectories(specPath.getParent());
            writeFile(specPath, "## ADDED Requirements\n\n### Requirement: " + cap + "\n\n(Generated by platform.)\n\n#### Scenario: placeholder\n- **WHEN** N/A\n- **THEN** N/A\n");
        }
        writeFile(changeDir.resolve("tasks.md"), buildTasksMd(p.getRequirementText() != null ? p.getRequirementText().trim() : "", CAPABILITIES));

        p.setChangeName(changeName);
        p.setChangePath(changeDir.toString());
        p.setStatus("ARTIFACTS_READY");
        repository.save(p);

        return changeDir.toString();
    }

    private static String toChangeName(String instanceId) {
        return "rtc-" + instanceId.replaceAll("[^a-zA-Z0-9-]", "-").replaceAll("-+", "-");
    }

    /**
     * If the work directory has no openspec/ directory, run `openspec init` so that
     * changes and artifacts can be created under openspec/changes/.
     */
    private void ensureOpenspecInitialized(Path workDir) throws IOException, InterruptedException {
        if (!Files.exists(workDir.resolve("openspec"))) {
            Files.createDirectories(workDir);
            int exit = run(workDir, "openspec", "init", ".");
            if (exit != 0) {
                throw new IOException("openspec init failed with exit " + exit + " at " + workDir);
            }
            log.info("Initialized openspec at {}", workDir);
        }
    }

    private int run(Path workDir, String... command) throws IOException, InterruptedException {
        ProcessBuilder pb = new ProcessBuilder(command);
        pb.directory(workDir.toFile());
        pb.redirectErrorStream(true);
        pb.environment().put("OPENSPEC_TELEMETRY", "0");
        Process p = pb.start();
        try (BufferedReader r = new BufferedReader(new InputStreamReader(p.getInputStream(), StandardCharsets.UTF_8))) {
            String line;
            while ((line = r.readLine()) != null) log.debug("openspec: {}", line);
        }
        boolean ok = p.waitFor(30, TimeUnit.SECONDS);
        if (!ok) p.destroyForcibly();
        return p.exitValue();
    }

    private void writeFile(Path path, String content) throws IOException {
        Files.createDirectories(path.getParent());
        Files.write(path, content.getBytes(StandardCharsets.UTF_8));
    }

    private String buildProposal(PipelineInstance p) {
        String req = p.getRequirementText() != null ? p.getRequirementText().trim() : "";
        String whySummary = req.isEmpty() ? "平台实例 " + p.getInstanceId() + " 暂无需求正文。" : firstLineOrSummary(req, 200);
        StringBuilder sb = new StringBuilder();
        sb.append("## Why\n\n");
        sb.append(whySummary);
        sb.append(" 本变更据此生成 proposal 与制品。\n\n## What Changes\n\n");
        List<String> points = extractRequirementPoints(req);
        if (points.isEmpty()) {
            sb.append("- 按需求实现功能与约束（见 design 与 tasks）。\n");
        } else {
            int limit = Math.min(points.size(), 6);
            for (int i = 0; i < limit; i++) {
                String s = points.get(i);
                if (s.length() > 60) s = s.substring(0, 60) + "...";
                sb.append("- ").append(s).append("\n");
            }
        }
        sb.append("\n## Capabilities\n\n### New Capabilities\n");
        for (String c : CAPABILITIES) sb.append("- `").append(c).append("`\n");
        sb.append("\n### Modified Capabilities\n\n(none)\n\n## Impact\n\n");
        sb.append("影响范围取决于需求实现，详见 design 与 specs。\n");
        return sb.toString();
    }

    private String firstLineOrSummary(String text, int maxLen) {
        String first = text.split("\\r?\\n")[0].trim();
        if (first.length() > maxLen) first = first.substring(0, maxLen) + "...";
        return first.isEmpty() ? "需求已提交。" : first;
    }

    /**
     * Build design.md per openspec schema: Context, Goals/Non-Goals, Decisions, Risks.
     * Content derived from requirement, not raw paste.
     */
    private String buildDesignFromRequirement(String requirementText) {
        String req = requirementText != null ? requirementText.trim() : "";
        String summary = req.isEmpty() ? "（无需求正文）" : firstLineOrSummary(req, 300);
        StringBuilder sb = new StringBuilder();
        sb.append("## Context\n\n");
        sb.append("本变更由需求驱动生成。需求摘要：").append(summary).append("\n\n");
        sb.append("## Goals / Non-Goals\n\n**Goals:**\n实现需求所述功能与约束。\n\n**Non-Goals:**\n不在本阶段实现的细节见 tasks。\n\n");
        sb.append("## Decisions\n\n按需求与 specs 实现；具体技术选型见需求或后续设计。\n\n");
        sb.append("## Risks / Trade-offs\n\n需求变更需同步更新 proposal、design、tasks。\n");
        return sb.toString();
    }

    /**
     * Build tasks.md content per openspec format: ## N. section and - [ ] N.M task lines.
     * Uses requirement text and capability list so the file is non-empty and parseable by apply.
     */
    private String buildTasksMd(String requirementText, List<String> capabilities) {
        StringBuilder sb = new StringBuilder();
        sb.append("## 1. Implementation\n\n");
        sb.append("- [ ] 1.1 Implement per specs\n");
        sb.append("- [ ] 1.2 Verify each capability meets requirement\n");
        int capIdx = 2;
        int maxCapTasks = 5;
        for (int i = 0; i < capabilities.size() && (capIdx - 2) < maxCapTasks; i++) {
            sb.append("- [ ] 1.").append(capIdx).append(" ").append(capabilities.get(i)).append("\n");
            capIdx++;
        }
        sb.append("\n## 2. Requirement breakdown\n\n");
        List<String> points = extractRequirementPoints(requirementText);
        if (points.isEmpty()) {
            sb.append("- [ ] 2.1 补充需求后重新生成或按 specs 实现\n");
        } else {
            int limit = Math.min(points.size(), 10);
            for (int i = 0; i < limit; i++) {
                String desc = points.get(i);
                if (desc.length() > 50) desc = desc.substring(0, 50) + "...";
                sb.append("- [ ] 2.").append(i + 1).append(" 实现: ").append(desc).append("\n");
            }
        }
        sb.append("\n## 3. Verification\n\n");
        sb.append("- [ ] 3.1 Run /opsx:apply and mark tasks complete\n");
        sb.append("- [ ] 3.2 Confirm behavior matches requirement\n");
        return sb.toString();
    }

    private List<String> extractRequirementPoints(String text) {
        if (text == null) return Arrays.asList();
        String[] raw = text.split("\\r?\\n|[。；;]");
        LinkedHashMap<String, Boolean> uniq = new LinkedHashMap<String, Boolean>();
        for (String r : raw) {
            String s = r == null ? "" : r.trim();
            if (s.isEmpty()) continue;
            if (s.length() > 120) s = s.substring(0, 120) + "...";
            uniq.put(s, Boolean.TRUE);
            if (uniq.size() >= 10) break;
        }
        return Arrays.asList(uniq.keySet().toArray(new String[0]));
    }
}
