package dev.home.platform.service;

import dev.home.platform.config.PlatformProperties;
import dev.home.platform.domain.PipelineInstance;
import dev.home.platform.domain.PipelineInstanceRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * Creates/updates openspec change and artifacts (proposal, design, specs, tasks).
 */
@Service
public class OpenspecService {

    private static final Logger log = LoggerFactory.getLogger(OpenspecService.class);
    private static final List<String> CAPABILITIES = Arrays.asList(
            "requirement-input", "design-generation", "openspec-integration", "cursor-integration", "pipeline-orchestration");

    private final PlatformProperties config;
    private final PipelineInstanceRepository repository;

    public OpenspecService(PlatformProperties config, PipelineInstanceRepository repository) {
        this.config = config;
        this.repository = repository;
    }

    /**
     * Ensure change exists, write/update proposal, design, specs, tasks. Returns change dir path.
     */
    public String runOpenspec(String instanceId) throws IOException, InterruptedException {
        PipelineInstance p = repository.findByInstanceId(instanceId)
                .orElseThrow(() -> new IllegalArgumentException("Instance not found: " + instanceId));
        String changeName = toChangeName(p.getInstanceId());
        Path workDir = Paths.get(config.getOpenspecWorkDir()).toAbsolutePath();
        Path changeDir = workDir.resolve("openspec").resolve("changes").resolve(changeName);

        if (!changeDir.toFile().exists()) {
            int exit = run(workDir, "openspec", "new", "change", changeName);
            if (exit != 0) throw new IOException("openspec new change failed with exit " + exit);
            log.info("Created openspec change: {}", changeName);
        } else {
            log.info("Reusing existing openspec change: {}", changeName);
        }

        writeFile(changeDir.resolve("proposal.md"), buildProposal(p));
        writeFile(changeDir.resolve("design.md"), p.getDesignContent() != null ? p.getDesignContent() : "# Design\n\n(empty)");
        for (String cap : CAPABILITIES) {
            Path specPath = changeDir.resolve("specs").resolve(cap).resolve("spec.md");
            Files.createDirectories(specPath.getParent());
            writeFile(specPath, "## ADDED Requirements\n\n### Requirement: " + cap + "\n\n(Generated by platform.)\n\n#### Scenario: placeholder\n- **WHEN** N/A\n- **THEN** N/A\n");
        }
        writeFile(changeDir.resolve("tasks.md"), buildTasksMd());

        p.setChangeName(changeName);
        p.setChangePath(changeDir.toString());
        p.setStatus("ARTIFACTS_READY");
        repository.save(p);

        return changeDir.toString();
    }

    private static String toChangeName(String instanceId) {
        return "rtc-" + instanceId.replaceAll("[^a-zA-Z0-9-]", "-").replaceAll("-+", "-");
    }

    private int run(Path workDir, String... command) throws IOException, InterruptedException {
        ProcessBuilder pb = new ProcessBuilder(command);
        pb.directory(workDir.toFile());
        pb.redirectErrorStream(true);
        Process p = pb.start();
        try (BufferedReader r = new BufferedReader(new InputStreamReader(p.getInputStream(), StandardCharsets.UTF_8))) {
            String line;
            while ((line = r.readLine()) != null) log.debug("openspec: {}", line);
        }
        boolean ok = p.waitFor(30, TimeUnit.SECONDS);
        if (!ok) p.destroyForcibly();
        return p.exitValue();
    }

    private void writeFile(Path path, String content) throws IOException {
        Files.createDirectories(path.getParent());
        Files.write(path, content.getBytes(StandardCharsets.UTF_8));
    }

    private String buildProposal(PipelineInstance p) {
        return "## Why\n\nGenerated from platform instance " + p.getInstanceId() + ".\n\n## What Changes\n\n- Requirement-driven design and openspec artifacts.\n\n## Capabilities\n\n### New Capabilities\n" +
                CAPABILITIES.stream().map(c -> "- `" + c + "`").reduce("", (a, b) -> a + "\n" + b) +
                "\n\n### Modified Capabilities\n\n(none)\n\n## Impact\n\nPlatform-generated change.\n";
    }

    private String buildTasksMd() {
        StringBuilder sb = new StringBuilder();
        sb.append("## 1. Implementation\n\n");
        sb.append("- [ ] 1.1 Implement per specs\n\n");
        return sb.toString();
    }
}
